去空行 g/^s*$/d
g ：全区命令
/ ：分隔符
^\s*$ ：匹配空行，其中^表示行首，\s表示空字符，包括空格和制表符，*重复0到n个前面的字符，$表示行尾。连起来就是匹配只有空字符的行，也就是空行。
/d ：删除该行

set tags=/root/practise/icrskice_5/src/icr_skice/tags 不能有空格
ctags -R --c++-kinds=+p --fields=+iaS --extra=+q

解决中文乱码：
set fileencodings=utf-8,gb2312,gb18030,gbk,ucs-bom,cp936,latin1
set enc=utf8
set fencs=utf8,gbk,gb2312,gb18030

