#include<syslog.h>
#include"hk_log.h"
int main()
{                               //identity     option           facility
    syslog_init();  //openlog("CAPTURE", LOG_ODELAY | LOG_PID, LOG_LOCAL1);  // Jun 26 14:01:51 90-20 CAPTURE[30633]: [DEBUG][1.c][main][6]start
    HK_LOG(MY_LOG_DEBUG,"start"); //#define HK_LOG(log_level, format, ...)  syslog( LOG_LOCAL1 | LOG_DEBUG, "[%s][%s][%s][%d]" format, log_level, __FILE__, __func__, __LINE__, ##__VA_ARGS__)
    HK_LOG(MY_LOG_DEBUG,"end");
    syslog_close();
    return 0;
}
/*
int main(int argc,char **argv)
{
    openlog("openlog_fun",LOG_CONS | LOG_PID,0);
    syslog(LOG_INFO,"this is a syslog test message generated by program %s\n",argv[0]);
    closelog();
    return 0;
}
*/
//修改 /etc/rsyslog.conf 
//service rsyslog restart 重启配置文件生效
//只能打印到/var/log 目录下, 其他目录不行
