.TH "PDNS_RECURSOR" "1" "March 2008" "" ""
.SH NAME
.PP
\f[B]pdns_recursor\f[] \- high\-performance, simple and secure recursing
nameserver
.SH SYNOPSIS
.PP
\f[B]pdns_recursor\f[] [\f[I]OPTION\f[]]...
.SH DESCRIPTION
.PP
pdns_recursor(1) is a high performance, simple and secure recursing
nameserver.
It currently powers over two million internet connections.
.PP
The recursor is configured via a configuration file, but each item in
that file can be overridden on the command line.
.PP
This manpage lists the core set of features needed to get the PowerDNS
recursor working, for full and up to date details head to
http://doc.powerdns.com/built\-in\-recursor.html
.SH EXAMPLES
.PP
To listen on 192.0.2.53 and allow the 192.0.2.0/24 subnet to recurse,
and run as a daemon, execute:
.PP
\f[C]#\ pdns_recursor\ \-\-local\-address=192.0.2.53\ \-\-allow\-from=192.0.2.0/24\ \-\-daemon\f[]
.PP
To stop the recursor by hand, run:
.PP
\f[C]#\ rec_control\ quit\f[]
.PP
However, the recommended way of starting and stopping the recursor is to
use the init.d script provided.
.SH OPTIONS
.PP
For authoritative listing of options, consult the online documentation
at http://doc.powerdns.com/md/recursor/settings/
.TP
.B \-\-allow\-from=\f[I]NETWORK\f[][,\f[I]NETWORK\f[]]...
If set, only allow these comma separated \f[I]NETWORK\f[]s, with network
mask to recurse.
For example: 192.0.2.0/24,203.0.113.128/25.
.RS
.RE
.TP
.B \-\-auth\-zones=\f[I]ZONENAME\f[]=\f[I]FILENAME\f[][,\f[I]ZONENAME\f[]=\f[I]FILENAME\f[]]...
Serve \f[I]ZONENAME\f[] from \f[I]FILENAME\f[] authoritatively.
For example:
ds9a.nl=/var/zones/ds9a.nl,powerdns.com=/var/zones/powerdns.com.
.RS
.RE
.TP
.B \-\-chroot=\f[I]DIRECTORY\f[]
chroot the process to \f[I]DIRECTORY\f[].
.RS
.RE
.TP
.B \-\-client\-tcp\-timeout=\f[I]NUM\f[]
Timeout in seconds when talking to TCP clients.
.RS
.RE
.TP
.B \-\-config\-dir=\f[I]DIRECTORY\f[]
Location of configuration directory (recursor.conf), the default depends
on the SYSCONFDIR option at build\-time, which is usually /etc/powerdns.
The default can be found with
\f[C]pdns_recursor\ \-\-config\ |\ grep\ \[aq]\ config\-dir=\[aq]\f[].
.RS
.RE
.TP
.B \-\-daemon
Operate as a daemon.
.RS
.RE
.TP
.B \-\-delegation\-only
Which domains we only accept delegations from (a Verisign special).
.RS
.RE
.TP
.B \-\-entropy\-source=\f[I]FILE\f[]
Read new entropy from \f[I]FILE\f[], defaults to /dev/urandom.
.RS
.RE
.TP
.B \-\-export\-etc\-hosts
If set, this flag will export the hostnames and IP addresses mentioned
in /etc/hosts.
.RS
.RE
.TP
.B \-\-forward\-zones=\f[I]ZONENAME\f[]=\f[I]ADDRESS\f[][,\f[I]ZONENAME\f[]=\f[I]ADDRESS\f[]]...
Queries for \f[I]ZONENAME\f[] will be forwarded to \f[I]ADDRESS\f[].
\f[I]ADDRESS\f[] should be an IP address, not a hostname (to prevent
chicken and egg problems).
Example: forward\-zones= ds9a.nl=213.244.168.210,
powerdns.com=127.0.0.1.
.RS
.RE
.TP
.B \-\-forward\-zones\-file=\f[I]FILENAME\f[]
Similar to \f[I]\-\-forward\-zones\f[], but read the options from
\f[I]FILENAME\f[].
\f[I]FILENAME\f[] should contain one zone per line, like:
ds9a.nl=213.244.168.210.
.RS
.RE
.TP
.B \-\-help
Show a summary of options.
.RS
.RE
.TP
.B \-\-hint\-file=\f[I]FILENAME\f[]
Load root hints from this \f[I]FILENAME\f[]
.RS
.RE
.TP
.B \-\-local\-address=\f[I]ADDRESS\f[][,\f[I]ADDRESS\f[]]...
Listen on \f[I]ADDRESS\f[], separated by spaces or commas.
.RS
.RE
.TP
.B \-\-local\-port=\f[I]PORT\f[]
Listen on \f[I]PORT\f[].
.RS
.RE
.TP
.B \-\-log\-common\-errors
If we should log rather common errors.
.RS
.RE
.TP
.B \-\-max\-cache\-entries=\f[I]NUM\f[]
Maximum number of entries in the main cache.
.RS
.RE
.TP
.B \-\-max\-negative\-ttl=\f[I]NUM\f[]
maximum number of seconds to keep a negative cached entry in memory.
.RS
.RE
.TP
.B \-\-max\-tcp\-clients=\f[I]NUM\f[]
Maximum number of simultaneous TCP clients.
.RS
.RE
.TP
.B \-\-max\-tcp\-per\-client
If set, maximum number of TCP sessions per client (IP address).
.RS
.RE
.TP
.B \-\-query\-local\-address=\f[I]ADDRESS\f[]
Use \f[I]ADDRESS\f[] as Source IP address when sending queries.
.RS
.RE
.TP
.B \-\-query\-local\-address6=\f[I]ADDRESS\f[]
Send out local IPv6 queries from \f[I]ADDRESS\f[].
Disabled by default, which also disables outgoing IPv6 support.
A useful setting is \[aq]::0\[aq].
.RS
.RE
.TP
.B \-\-quiet
Suppress logging of questions and answers.
.RS
.RE
.TP
.B \-\-server\-id=\f[I]TEXT\f[]
Return \f[I]TEXT\f[] when queried for \[aq]server.id\[aq] TXT, defaults
to hostname.
.RS
.RE
.TP
.B \-\-serve\-rfc1918
On by default, this makes the server authoritatively aware of:
10.in\-addr.arpa, 168.192.in\-addr.arpa and 16\-31.172.in\-addr.arpa,
which saves load on the AS112 servers.
Individual parts of these zones can still be loaded or forwarded.
.RS
.RE
.TP
.B \-\-setgid=\f[I]GID\f[]
If set, change group id to \f[I]GID\f[] for more security.
.RS
.RE
.TP
.B \-\-setuid=\f[I]UID\f[]
If set, change user id to \f[I]UID\f[] for more security.
.RS
.RE
.TP
.B \-\-single\-socket
If set, only use a single socket for outgoing queries.
.RS
.RE
.TP
.B \-\-socket\-dir=\f[I]DIRECTORY\f[]
The controlsocket will live in \f[I]DIRECTORY\f[].
.RS
.RE
.TP
.B \-\-spoof\-nearmiss\-max=\f[I]NUM\f[]
If non\-zero, assume spoofing after this many near misses.
.RS
.RE
.TP
.B \-\-trace
if we should output heaps of logging.
.RS
.RE
.TP
.B \-\-version\-string=\f[I]TEXT\f[]
\f[I]TEXT\f[] will be reported on version.pdns or version.bind queries.
.RS
.RE
.SH BUGS
.PP
None known.
File new ones at https://github.com/PowerDNS/pdns/issues.
.SH RESOURCES
.PP
Website: http://www.powerdns.com, https://github.com/PowerDNS/pdns
.SH SEE ALSO
.PP
rec_control(1)
.SH AUTHORS
PowerDNS.COM BV.
