.TH "REC_CONTROL" "1" "April 2006" "" ""
.SH NAME
.PP
rec_control \- control pdns_recursor
.SH SYNOPSIS
.PP
\f[B]rec_control\f[] [\f[I]OPTION\f[]]...
\f[I]COMMAND\f[] [\f[I]COMMAND\-OPTION\f[]]...
.SS DESCRIPTION
.PP
\f[B]rec_control\f[] allows the operator to control a running instance
of the pdns_recursor.
.PP
The commands that can be passed to the recursor are described on
http://doc.powerdns.com/md/recursor/running/#rec_control\-commands
.SH EXAMPLES
.PP
To stop the recursor by hand, run:
.PP
\f[C]#\ rec_control\ quit\f[]
.PP
To dump the cache to disk, execute:
.PP
\f[C]#\ rec_control\ dump\-cache\ /tmp/the\-cache\f[]
.SH OPTIONS
.TP
.B \-\-help
provide this helpful message.
.RS
.RE
.TP
.B \-\-config\-dir=\f[I]PATH\f[]
Directory where the recursor.conf lives.
.RS
.RE
.TP
.B \-\-socket\-dir=\f[I]PATH\f[]
Where the controlsocket will live, please use \f[B]\-\-config\-dir\f[]
instead.
.RS
.RE
.TP
.B \-\-socket\-pid=\f[I]PID\f[]
When running in SMP mode, pid of \f[B]pdns_recursor\f[] to control.
.RS
.RE
.TP
.B \-\-timeout=\f[I]NUM\f[]
Number of seconds to wait for the remote PowerDNS Recursor to respond.
Set to 0 for infinite.
.RS
.RE
.SH COMMANDS
.TP
.B add\-nta \f[I]DOMAIN\f[] [\f[I]REASON\f[]]
Add a Negative Trust Anchor for \f[I]DOMAIN\f[], suffixed optionally
with \f[I]REASON\f[].
.RS
.RE
.TP
.B add\-ta \f[I]DOMAIN\f[] \f[I]DSRECORD\f[]
Add a Trust Anchor for \f[I]DOMAIN\f[] with DS record data
\f[I]DSRECORD\f[].
This adds the new Trust Anchor to the existing set of Trust Anchors for
\f[I]DOMAIN\f[].
.RS
.RE
.TP
.B current\-queries
Shows the currently active queries.
.RS
.RE
.TP
.B clear\-nta \f[I]DOMAIN\f[]...
Remove Negative Trust Anchor for one or more \f[I]DOMAIN\f[]s.
Set domain to \f[C]\[aq]*\[aq]\f[] to remove all NTA\[aq]s.
.RS
.RE
.TP
.B clear\-ta [\f[I]DOMAIN\f[]]...
Remove Trust Anchor for one or more \f[I]DOMAIN\f[]s.
Note that removing the root trust anchor is not possible.
.RS
.RE
.TP
.B dump\-cache \f[I]FILENAME\f[]
Dumps the entire cache to \f[I]FILENAME\f[].
This file should not exist already, PowerDNS will refuse to overwrite
it.
While dumping, the recursor will not answer questions.
.RS
.RE
.TP
.B dump\-edns \f[I]FILENAME\f[]
Dumps the EDNS status to the filename mentioned.
This file should not exist already, PowerDNS will refuse to overwrite
it.
While dumping, the recursor will not answer questions.
.RS
.RE
.TP
.B dump\-nsspeeds \f[I]FILENAME\f[]
Dumps the nameserver speed statistics to the \f[I]FILENAME\f[]
mentioned.
This file should not exist already, PowerDNS will refuse to overwrite
it.
While dumping, the recursor will not answer questions.
.RS
.RE
.TP
.B get \f[I]STATISTIC\f[] [\f[I]STATISTIC\f[]]...
Retrieve a statistic.
For items that can be queried, see
http://doc.powerdns.com/md/recursor/stats/
.RS
.RE
.TP
.B get\-all
Retrieve all known statistics.
.RS
.RE
.TP
.B get\-ntas
Get a list of the currently configured Negative Trust Anchors.
.RS
.RE
.TP
.B get\-tas
Get a list of the currently configured Trust Anchors.
.RS
.RE
.TP
.B get\-parameter \f[I]KEY\f[] [\f[I]KEY\f[]]...
Retrieves the specified configuration parameter(s).
.RS
.RE
.TP
.B get\-qtypelist
Retrieves QType statistics.
Queries from cache aren\[aq]t being counted yet.
.RS
.RE
.TP
.B help
Shows a list of supported commands.
.RS
.RE
.TP
.B ping
Check if server is alive.
.RS
.RE
.TP
.B quit
Request shutdown of the recursor.
.RS
.RE
.TP
.B quit\-nicely
Request nice shutdown of the recursor.
.RS
.RE
.TP
.B reload\-acls
Reloads ACLs.
.RS
.RE
.TP
.B reload\-lua\-script [\f[I]FILENAME\f[]]
(Re)loads Lua script \f[I]FILENAME\f[].
If \f[I]FILENAME\f[] is empty, attempt to reload the currently loaded
script.
This replaces the script currently loaded.
.RS
.RE
.TP
.B reload\-lua\-config [\f[I]FILENAME\f[]]
(Re)loads Lua configuration \f[I]FILENAME\f[].
If \f[I]FILENAME\f[] is empty, attempt to reload the currently loaded
file.
Note that \f[I]FILENAME\f[] will be fully executed, any settings changed
at runtime that are not modified in this file, will still be active.
Reloading RPZ, especially by AXFR, can take some time; during which the
recursor will not answer questions.
.RS
.RE
.TP
.B reload\-zones
Reload authoritative and forward zones.
Retains current configuration in case of errors.
.RS
.RE
.TP
.B set\-carbon\-server \f[I]CARBON SERVER\f[] [\f[I]CARBON OURNAME\f[]]
Set the carbon\-server setting to \f[I]CARBON SERVER\f[].
If \f[I]CARBON OURNAME\f[] is not empty, also set the carbon\-ourname
setting to \f[I]CARBON OURNAME\f[].
.RS
.RE
.TP
.B set\-dnssec\-log\-bogus \f[I]SETTING\f[]
Set dnssec\-log\-bogus setting to \f[I]SETTING\f[].
Set to \[aq]on\[aq] or \[aq]yes\[aq] to log DNSSEC validation failures
and to \[aq]no\[aq] or \[aq]off\[aq] to disable logging these failures.
.RS
.RE
.TP
.B set\-minimum\-ttl \f[I]NUM\f[]
Set minimum\-ttl\-override to \f[I]NUM\f[].
.RS
.RE
.TP
.B top\-queries
Shows the top\-20 queries.
Statistics are over the last \[aq]stats\-ringbuffer\-entries\[aq]
queries.
.RS
.RE
.TP
.B top\-pub\-queries
Shows the top\-20 queries grouped by public suffix list.
Statistics are over the last \[aq]stats\-ringbuffer\-entries\[aq]
queries.
.RS
.RE
.TP
.B top\-largeanswer\-remotes
Shows the top\-20 remote hosts causing large answers.
Statistics are over the last \[aq]stats\-ringbuffer\-entries\[aq]
queries.
.RS
.RE
.TP
.B top\-remotes
Shows the top\-20 most active remote hosts.
Statistics are over the last \[aq]stats\-ringbuffer\-entries\[aq]
queries.
.RS
.RE
.TP
.B top\-servfail\-queries
Shows the top\-20 queries causing servfail responses.
Statistics are over the last \[aq]stats\-ringbuffer\-entries\[aq]
queries.
.RS
.RE
.TP
.B top\-pub\-servfail\-queries
Shows the top\-20 queries causing servfail responses grouped by public
suffix list.
Statistics are over the last \[aq]stats\-ringbuffer\-entries\[aq]
queries.
.RS
.RE
.TP
.B top\-servfail\-remotes
Shows the top\-20 most active remote hosts causing servfail responses.
Statistics are over the last \[aq]stats\-ringbuffer\-entries\[aq]
queries.
.RS
.RE
.TP
.B trace\-regex \f[I]REGEX\f[]
Emit resolution trace for matching queries.
Empty regex to disable trace.
.RS
.RE
.TP
.B unload\-lua\-script
Unloads Lua script.
.RS
.RE
.TP
.B version
Report running version.
.RS
.RE
.TP
.B wipe\-cache \f[I]DOMAIN\f[] [\f[I]DOMAIN\f[]] [...]
Wipe entries for \f[I]DOMAIN\f[] (exact name match) from the cache.
This is useful if, for example, an important server has a new IP
address, but the TTL has not yet expired.
Multiple domain names can be passed.
\f[I]DOMAIN\f[] can be suffixed with a
\[aq]ʹ\f[I]t\f[]\f[I]o\f[]\f[I]d\f[]\f[I]e\f[]\f[I]l\f[]\f[I]e\f[]\f[I]t\f[]\f[I]e\f[]\f[I]t\f[]\f[I]h\f[]\f[I]e\f[]\f[I]w\f[]\f[I]h\f[]\f[I]o\f[]\f[I]l\f[]\f[I]e\f[]\f[I]t\f[]\f[I]r\f[]\f[I]e\f[]\f[I]e\f[]\f[I]f\f[]\f[I]r\f[]\f[I]o\f[]\f[I]m\f[]\f[I]t\f[]\f[I]h\f[]\f[I]e\f[]\f[I]c\f[]\f[I]a\f[]\f[I]c\f[]\f[I]h\f[]\f[I]e\f[].\f[I]i\f[].\f[I]e\f[].ʹ\f[I]p\f[]\f[I]o\f[]\f[I]w\f[]\f[I]e\f[]\f[I]r\f[]\f[I]d\f[]\f[I]n\f[]\f[I]s\f[].\f[I]c\f[]\f[I]o\f[]\f[I]m\f[]\[aq]
will remove all cached entries under and including the powerdns.com
name.
.RS
.RE
.SH BUGS
.PP
None known.
File new ones at https://github.com/PowerDNS/pdns/issues.
.SH RESOURCES
.PP
Website: https://docs.powerdns.com, https://www.powerdns.com
.SH SEE ALSO
.PP
pdns_recursor(1)
.SH AUTHORS
PowerDNS.COM BV.
